# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68de2bafc8a229210080c0a0ccc2b2ba3393fd1d36dcc00be976a3ab10529f13f6edfbc66cf094d133a4d022ff1543dadda0ea5609d22dcaede07e93b31796d3

test:
  secret_key_base: 9a82933237b8bc818793888cdaf1f0623f71157eec43cb7a148d30894400f6fd0209e204921133767020beaee5b762e07c9a31202e8538e473b2b457f86058a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
